[package]
name = "molweaver"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
egui = "0.27"
egui-wgpu = "0.27"
egui-winit = "0.27"
glam = "0.27"
pollster = "0.3"
wgpu = "0.19"
winit = "0.29"
